controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tinymovr_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

tinymovr_joint_trajectory_controller:
  ros__parameters:
    joints:
      - test_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity